//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cronlog
    {
        public long CLID { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Email { get; set; }
        public Nullable<int> RentalId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Mode { get; set; }
        public string TxnId { get; set; }
        public Nullable<int> FinalOrderId { get; set; }
        public string Res { get; set; }
    }
}
