//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class damaged_item
    {
        public long id { get; set; }
        public string pro_id { get; set; }
        public long quantity { get; set; }
        public System.DateTime date { get; set; }
        public string how_it_happen { get; set; }
        public string who_is_responsible { get; set; }
        public string submitter { get; set; }
        public System.DateTime date_time { get; set; }
        public string type_d { get; set; }
        public decimal value_d { get; set; }
        public string rep_sub_name { get; set; }
    }
}
