//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class driver
    {
        public long id { get; set; }
        public string user_type { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public string email { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string address { get; set; }
        public string address2 { get; set; }
        public string phone { get; set; }
        public string zip { get; set; }
        public System.DateTime date { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string licence { get; set; }
        public long inactive { get; set; }
        public string truck { get; set; }
        public string security_question { get; set; }
        public string security_answer { get; set; }
        public string exp_date { get; set; }
        public System.DateTime dob { get; set; }
        public string photo { get; set; }
        public string home_phone { get; set; }
        public System.DateTime hire_dt { get; set; }
    }
}
