//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_module
    {
        public int user_id { get; set; }
        public int truck { get; set; }
        public int truck_add { get; set; }
        public int truck_edit { get; set; }
        public int truck_delete { get; set; }
        public int driver { get; set; }
        public int driver_add { get; set; }
        public int driver_edit { get; set; }
        public int driver_delete { get; set; }
        public int inventory { get; set; }
        public int inventory_add { get; set; }
        public int inventory_edit { get; set; }
        public int inventory_delete { get; set; }
        public int order { get; set; }
        public int order_add { get; set; }
        public int order_edit { get; set; }
        public int order_delete { get; set; }
        public int invoice { get; set; }
        public int invoice_add { get; set; }
        public int invoice_edit { get; set; }
        public int invoice_delete { get; set; }
        public int customer { get; set; }
        public int customer_add { get; set; }
        public int customer_edit { get; set; }
        public int customer_delete { get; set; }
        public long order_qb { get; set; }
        public long invoice_qb { get; set; }
        public long customer_qb { get; set; }
        public int emp { get; set; }
        public int emp_add { get; set; }
        public int emp_edit { get; set; }
        public int emp_delete { get; set; }
    }
}
