//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_module_driver
    {
        public int user_id { get; set; }
        public int my_profile { get; set; }
        public int my_profile_add { get; set; }
        public int my_profile_edit { get; set; }
        public int my_profile_delete { get; set; }
        public int order_dtl { get; set; }
        public int order_dtl_add { get; set; }
        public int order_dtl_edit { get; set; }
        public int order_dtl_delete { get; set; }
        public int truck_inventory { get; set; }
        public int truck_inventory_add { get; set; }
        public int truck_inventory_edit { get; set; }
        public int truck_inventory_delete { get; set; }
        public int inventory { get; set; }
        public int inventory_add { get; set; }
        public int inventory_edit { get; set; }
        public int inventory_delete { get; set; }
        public int add_order { get; set; }
        public int add_order_add { get; set; }
        public int add_order_edit { get; set; }
        public int add_order_delete { get; set; }
    }
}
