//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class edit_module
    {
        public int user_id { get; set; }
        public int category { get; set; }
        public int inventory { get; set; }
        public int user_setup { get; set; }
        public int purchase { get; set; }
        public int customer_rentals { get; set; }
        public int return_tool { get; set; }
        public int mobile_tool { get; set; }
        public int tax { get; set; }
        public int exchange { get; set; }
    }
}
