//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class final_order_dtls
    {
        public long id { get; set; }
        public long cart_id { get; set; }
        public long service { get; set; }
        public long category { get; set; }
        public long product_id { get; set; }
        public string size { get; set; }
        public string color { get; set; }
        public decimal sale_price { get; set; }
        public long quantity { get; set; }
        public decimal total { get; set; }
        public string design_image { get; set; }
        public int price_update { get; set; }
        public long pending_qty { get; set; }
        public long minus_qty { get; set; }
        public long left_qty { get; set; }
        public long original { get; set; }
        public string TxnLineId { get; set; }
        public string EditSequence { get; set; }
    }
}
