//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ecommerce2Entities : DbContext
    {
        public ecommerce2Entities()
            : base("name=ecommerce2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cart> cart { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<company> company { get; set; }
        public virtual DbSet<content> content { get; set; }
        public virtual DbSet<cronlog> cronlog { get; set; }
        public virtual DbSet<cronlogsus> cronlogsus { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<customer_invoicing> customer_invoicing { get; set; }
        public virtual DbSet<damaged_item> damaged_item { get; set; }
        public virtual DbSet<driver> driver { get; set; }
        public virtual DbSet<driver_final_order> driver_final_order { get; set; }
        public virtual DbSet<driver_final_order_dtls> driver_final_order_dtls { get; set; }
        public virtual DbSet<driver_final_order_dtls_temp> driver_final_order_dtls_temp { get; set; }
        public virtual DbSet<dt_module> dt_module { get; set; }
        public virtual DbSet<dt_module_driver> dt_module_driver { get; set; }
        public virtual DbSet<dt_role> dt_role { get; set; }
        public virtual DbSet<dt_state> dt_state { get; set; }
        public virtual DbSet<dt_welcome> dt_welcome { get; set; }
        public virtual DbSet<edit_module> edit_module { get; set; }
        public virtual DbSet<email_attach> email_attach { get; set; }
        public virtual DbSet<failedorders> failedorders { get; set; }
        public virtual DbSet<final_order> final_order { get; set; }
        public virtual DbSet<final_order_dtls> final_order_dtls { get; set; }
        public virtual DbSet<final_order_dtls_temp> final_order_dtls_temp { get; set; }
        public virtual DbSet<logo> logo { get; set; }
        public virtual DbSet<logo_pages> logo_pages { get; set; }
        public virtual DbSet<manage_rentals> manage_rentals { get; set; }
        public virtual DbSet<map> map { get; set; }
        public virtual DbSet<newsletter> newsletter { get; set; }
        public virtual DbSet<noti_user> noti_user { get; set; }
        public virtual DbSet<payment> payment { get; set; }
        public virtual DbSet<payment_order> payment_order { get; set; }
        public virtual DbSet<pre_final_order_dtls> pre_final_order_dtls { get; set; }
        public virtual DbSet<pre_final_order_dtls_tmp> pre_final_order_dtls_tmp { get; set; }
        public virtual DbSet<product_user_price> product_user_price { get; set; }
        public virtual DbSet<promo> promo { get; set; }
        public virtual DbSet<qblog> qblog { get; set; }
        public virtual DbSet<qblog_customer> qblog_customer { get; set; }
        public virtual DbSet<qblog_inventory> qblog_inventory { get; set; }
        public virtual DbSet<quickbooks_config> quickbooks_config { get; set; }
        public virtual DbSet<quickbooks_log> quickbooks_log { get; set; }
        public virtual DbSet<quickbooks_oauth> quickbooks_oauth { get; set; }
        public virtual DbSet<quickbooks_queue> quickbooks_queue { get; set; }
        public virtual DbSet<quickbooks_recur> quickbooks_recur { get; set; }
        public virtual DbSet<quickbooks_ticket> quickbooks_ticket { get; set; }
        public virtual DbSet<quickbooks_user> quickbooks_user { get; set; }
        public virtual DbSet<rentals_item> rentals_item { get; set; }
        public virtual DbSet<revised_invoice> revised_invoice { get; set; }
        public virtual DbSet<sent_mail> sent_mail { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<service_menu> service_menu { get; set; }
        public virtual DbSet<shipping_address> shipping_address { get; set; }
        public virtual DbSet<sub_service> sub_service { get; set; }
        public virtual DbSet<subscribe> subscribe { get; set; }
        public virtual DbSet<truck> truck { get; set; }
        public virtual DbSet<truck_inventory> truck_inventory { get; set; }
        public virtual DbSet<truck_inventory_product> truck_inventory_product { get; set; }
        public virtual DbSet<truck_maintenance> truck_maintenance { get; set; }
        public virtual DbSet<truck_order> truck_order { get; set; }
        public virtual DbSet<truck_order_item> truck_order_item { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_hit_status> user_hit_status { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<vendor> vendor { get; set; }
        public virtual DbSet<vendor_item> vendor_item { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<product_old> product_old { get; set; }
    }
}
