//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class newsletter
    {
        public int id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string added_on { get; set; }
        public System.DateTime start_dt { get; set; }
        public System.DateTime end_dt { get; set; }
    }
}
