//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class noti_user
    {
        public long id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public long check_val { get; set; }
        public string user_id { get; set; }
    }
}
