//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public long id { get; set; }
        public string customer { get; set; }
        public string payment_type { get; set; }
        public string cheque_no { get; set; }
        public string cheque_dtl { get; set; }
        public string cash_name { get; set; }
        public string cash_phone { get; set; }
        public string cc_number { get; set; }
        public string cc_type { get; set; }
        public string cc_user_name { get; set; }
        public System.DateTime expiry_date { get; set; }
        public decimal total_amount { get; set; }
        public System.DateTime date_time { get; set; }
    }
}
