//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public long id { get; set; }
        public int service_id { get; set; }
        public string cat_id { get; set; }
        public string company_id { get; set; }
        public string band_name { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string product_logo { get; set; }
        public string small_image { get; set; }
        public decimal price { get; set; }
        public string size { get; set; }
        public System.DateTime date { get; set; }
        public string status { get; set; }
        public string stock_status { get; set; }
        public string photo1 { get; set; }
        public string photo2 { get; set; }
        public string photo3 { get; set; }
        public string type { get; set; }
        public string typo { get; set; }
        public string website { get; set; }
        public string item_id { get; set; }
        public string sku { get; set; }
        public string left_menu { get; set; }
        public int quantity { get; set; }
        public int check_tax { get; set; }
        public string tax { get; set; }
        public long minquantity { get; set; }
        public string res_list_id { get; set; }
    }
}
