//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class quickbooks_oauth
    {
        public long quickbooks_oauth_id { get; set; }
        public string app_username { get; set; }
        public string app_tenant { get; set; }
        public string oauth_request_token { get; set; }
        public string oauth_request_token_secret { get; set; }
        public string oauth_access_token { get; set; }
        public string oauth_access_token_secret { get; set; }
        public string qb_realm { get; set; }
        public string qb_flavor { get; set; }
        public string qb_user { get; set; }
        public System.DateTime request_datetime { get; set; }
        public Nullable<System.DateTime> access_datetime { get; set; }
        public Nullable<System.DateTime> touch_datetime { get; set; }
    }
}
