//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class quickbooks_log
    {
        public long quickbooks_log_id { get; set; }
        public Nullable<long> quickbooks_ticket_id { get; set; }
        public long batch { get; set; }
        public string msg { get; set; }
        public System.DateTime log_datetime { get; set; }
    }
}
