//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class quickbooks_ticket
    {
        public long quickbooks_ticket_id { get; set; }
        public string qb_username { get; set; }
        public System.Guid ticket { get; set; }
        public Nullable<long> processed { get; set; }
        public string lasterror_num { get; set; }
        public string lasterror_msg { get; set; }
        public string ipaddr { get; set; }
        public System.DateTime write_datetime { get; set; }
        public System.DateTime touch_datetime { get; set; }
    }
}
