//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class quickbooks_user
    {
        public string qb_username { get; set; }
        public string qb_password { get; set; }
        public string qb_company_file { get; set; }
        public Nullable<long> qbwc_wait_before_next_update { get; set; }
        public Nullable<long> qbwc_min_run_every_n_seconds { get; set; }
        public string status { get; set; }
        public System.DateTime write_datetime { get; set; }
        public System.DateTime touch_datetime { get; set; }
    }
}
