//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class rentals_item
    {
        public long id { get; set; }
        public string rental_id { get; set; }
        public string item_id { get; set; }
        public string item_name { get; set; }
        public decimal cust_rent { get; set; }
        public string term { get; set; }
        public string size { get; set; }
        public System.DateTime rental_start_date { get; set; }
        public System.DateTime rental_end_date { get; set; }
        public long quantity { get; set; }
    }
}
