//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sent_mail
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string sub { get; set; }
        public string message { get; set; }
        public System.DateTime date_time { get; set; }
    }
}
