//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_service
    {
        public long id { get; set; }
        public long service_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string photo { get; set; }
        public string video { get; set; }
        public System.DateTime added_on { get; set; }
        public string status { get; set; }
        public string radio { get; set; }
    }
}
