//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class truck_order
    {
        public long id { get; set; }
        public long truck_id { get; set; }
        public long driver_id { get; set; }
        public System.DateTime shipping_date { get; set; }
        public System.DateTime date_time { get; set; }
        public string status { get; set; }
    }
}
