//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class truck_inventory_product
    {
        public long id { get; set; }
        public long truck_inventory_id { get; set; }
        public long service { get; set; }
        public long category { get; set; }
        public long product_id { get; set; }
        public long quantity { get; set; }
        public long customer_id { get; set; }
    }
}
