//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class truck_maintenance
    {
        public long id { get; set; }
        public long out_of_service { get; set; }
        public System.DateTime date { get; set; }
        public string comment { get; set; }
        public string mileage { get; set; }
        public System.DateTime m_date { get; set; }
        public string m_type { get; set; }
        public string service_company { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string phone { get; set; }
        public decimal cost { get; set; }
        public string paid_by { get; set; }
        public string m_by { get; set; }
        public string m_comment { get; set; }
        public System.DateTime date_time { get; set; }
        public string truck_id { get; set; }
    }
}
