//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class truck
    {
        public long id { get; set; }
        public string truck_no { get; set; }
        public string made { get; set; }
        public string model { get; set; }
        public string year { get; set; }
        public string mileage { get; set; }
        public string color { get; set; }
        public string purchased_from { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string phone { get; set; }
        public decimal company_cost { get; set; }
        public System.DateTime purchased_date { get; set; }
        public string condition { get; set; }
        public string photo { get; set; }
        public string description { get; set; }
        public long inactive { get; set; }
        public System.DateTime date { get; set; }
        public string lp { get; set; }
        public string vin { get; set; }
    }
}
