//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public long id { get; set; }
        public string user_type { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public string email { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string address { get; set; }
        public string address2 { get; set; }
        public string phone { get; set; }
        public string zip { get; set; }
        public string place { get; set; }
        public System.DateTime date { get; set; }
        public int publish { get; set; }
        public string photo { get; set; }
        public int shop_id { get; set; }
        public int num_list { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string pin { get; set; }
        public string merchant_acct { get; set; }
        public string auth_login_id { get; set; }
        public string auth_trans_key { get; set; }
        public string company { get; set; }
        public string contact_name { get; set; }
        public string contact_position { get; set; }
        public string contact_email { get; set; }
        public string contact_phone { get; set; }
        public string qb_id { get; set; }
        public int quickbook_check { get; set; }
        public string customer_invoice { get; set; }
        public string fax { get; set; }
        public decimal fs { get; set; }
        public string master_cust { get; set; }
        public string billing_address { get; set; }
        public string billing_address2 { get; set; }
        public string ChainStoreNum { get; set; }
        public string Area { get; set; }
        public string CreditClass { get; set; }
        public string CreditLimt { get; set; }
        public string TaxAuth { get; set; }
        public string TaxStatus { get; set; }
        public string PriceList { get; set; }
        public string DateLastDelv { get; set; }
        public string HHinvoiceCopies { get; set; }
        public string Business { get; set; }
        public string Acquisition { get; set; }
        public string PurchOrder { get; set; }
        public string NextDelvDate { get; set; }
        public string quickbooks_listid { get; set; }
        public string quickbooks_editsequence { get; set; }
        public string quickbooks_errnum { get; set; }
        public string quickbooks_errmsg { get; set; }
        public string ListID { get; set; }
        public string EditSequence { get; set; }
        public long check_tax { get; set; }
        public string cust_com_l { get; set; }
        public string res_list_id { get; set; }
        public string po_no { get; set; }
    }
}
