//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_hit_status
    {
        public long id { get; set; }
        public string page { get; set; }
        public string ip_address { get; set; }
        public long hit_count { get; set; }
        public System.DateTime date_time { get; set; }
    }
}
