//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public string uname { get; set; }
        public string pass { get; set; }
        public int role_id { get; set; }
        public int ind_id { get; set; }
        public string type { get; set; }
        public int inactive { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public System.DateTime date_time { get; set; }
        public string email { get; set; }
        public string tax { get; set; }
        public string address { get; set; }
        public string address2 { get; set; }
        public string phone { get; set; }
        public string zip { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string company { get; set; }
        public string licence { get; set; }
        public string security_question { get; set; }
        public string security_answer { get; set; }
        public string exp_date { get; set; }
        public System.DateTime dob { get; set; }
        public string photo { get; set; }
        public string home_phone { get; set; }
        public System.DateTime hire_dt { get; set; }
        public string position { get; set; }
    }
}
