//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor
    {
        public long id { get; set; }
        public string com_from { get; set; }
        public string com_add { get; set; }
        public string com_city { get; set; }
        public string state { get; set; }
        public string com_zip { get; set; }
        public string com_phone { get; set; }
        public long com_qua { get; set; }
        public System.DateTime com_date { get; set; }
        public decimal com_price { get; set; }
        public System.DateTime date_time { get; set; }
        public long product_id { get; set; }
        public string sku { get; set; }
        public string size { get; set; }
        public string pur_name { get; set; }
    }
}
