//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutiveRefreshment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor_item
    {
        public long id { get; set; }
        public string sku { get; set; }
        public string product_id { get; set; }
        public string size { get; set; }
        public long qty { get; set; }
        public decimal cost { get; set; }
        public System.DateTime date_time { get; set; }
        public string pr_name { get; set; }
        public long qty_in { get; set; }
        public string vendor_id { get; set; }
    }
}
